
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content" style="min-height:1269px">
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            Sides <small>Ajout d'une Side</small>
        </h3>
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="<?php echo $this->url("home_connected") ?>">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <i class="fa fa-fire"></i>
                    <a href="<?php echo $this->url("home_admin") ?>">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <i class="fa fa-map-marker"></i>
                    <a href="<?php echo $this->url("home_admin", array("controller" => "side")) ?>">Sides</a>
                    <i class="fa fa-angle-right"></i>
                </li>
            </ul>
            <div class="page-toolbar">
                <div class="btn-group pull-right">
                    <a href="<?php echo $this->url("home_admin/common", array("controller" => "side", "action" => "list")) ?>"  class="btn btn-fit-height btn-danger" data-delay="1000" data-close-others="true">
                        <i class="fa fa-mail-reply"></i>&nbsp; Retour
                    </a>
                </div>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-equalizer font-red-sunglo"></i>
                            <span class="caption-subject font-red-sunglo bold uppercase">Ajout d'une Side</span>
                            <span class="caption-helper">Définition d'une Side</span>
                        </div>
                        <div class="actions">
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="#" class="form-horizontal">
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Nom</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control input-inline input-medium" placeholder="Nom de la Région">
                                        <span class='help-inline'>Nom Unique</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Port Serveur Arma3</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control input-inline input-medium" placeholder="Port arma3">
                                        <span class='help-inline'>Auto-Vérifier par l'application</span>
                                    </div>

                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-4 control-label">Armée de Régulation</label>
                                <div class="col-md-4">
                                    <select class="form-control input-inline input-medium">
                                        <option>Option 1</option>
                                        <option>Option 2</option>
                                        <option>Option 3</option>
                                        <option>Option 4</option>
                                        <option>Option 5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label">Police Militaire Locale</label>
                                <div class="col-md-4">
                                    <select class="form-control input-inline input-medium">
                                        <option>Option 1</option>
                                        <option>Option 2</option>
                                        <option>Option 3</option>
                                        <option>Option 4</option>
                                        <option>Option 5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label">Groupe Insurgé</label>
                                <div class="col-md-4">
                                    <select class="form-control input-inline input-medium">
                                        <option>Option 1</option>
                                        <option>Option 2</option>
                                        <option>Option 3</option>
                                        <option>Option 4</option>
                                        <option>Option 5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-4">
                                    <a class="btn btn-success" href="<?php echo $this->url("home_admin/common", array("controller" => "side", "action" => "add")) ?>">
                                        <i class="fa fa-plus "></i>  Ajouter une Side
                                    </a>
                                </div>
                            </div>
                            <hr>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-5 col-md-2">
                                        <button type="submit" class="btn green">Créer</button>
                                        <a href='<?php echo $this->url("home_admin/common", array("controller" => "region", "action" => "list")) ?>' class="btn default">Annuler</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<!-- END CONTENT -->