
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content" style="min-height:1269px">
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            Sides <small>Ajout d'une Side</small>
        </h3>
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="<?php echo $this->url("home_connected") ?>">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <i class="fa fa-fire"></i>
                    <a href="<?php echo $this->url("home_admin") ?>">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <i class="fa fa-users"></i>
                    <a href="<?php echo $this->url("home_admin/common", array("controller" => "side")) ?>">Sides</a>
                    <i class="fa fa-angle-right"></i>
                </li>
            </ul>
            <div class="page-toolbar">
                <div class="btn-group pull-right">
                    <a href="<?php echo $this->url("home_admin/common", array("controller" => "side", "action" => "list")) ?>"  class="btn btn-fit-height btn-danger" data-delay="1000" data-close-others="true">
                        <i class="fa fa-mail-reply"></i>&nbsp; Retour
                    </a>
                </div>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-equalizer font-red-sunglo"></i>
                            <span class="caption-subject font-red-sunglo bold uppercase">Ajout d'une Side</span>
                            <span class="caption-helper">Définition d'une Side</span>
                        </div>
                        <div class="actions">
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <form action="<?php echo $this->url("home_admin/common", array("controller" => "side", "action" => "add")) ?>" class="form-horizontal" method="post">
                            <div class="form-body">
                                <?php if (isset($this->errormessage)): ?>
                                    <div class="form-group">
                                        <div class="alert alert-danger col-md-4 col-md-offset-3">
                                            <strong>Erreur :</strong>
                                            <?php echo $this->errormessage ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if (isset($this->warnmessage)): ?>
                                    <div class="form-group">
                                        <div class="alert alert-warning col-md-4 col-md-offset-3">
                                            <strong>Erreur :</strong>
                                            <?php echo $this->warnmessage ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php
                                if (count($this->addSideForm->get("shortlabel")->getMessages()) > 0) {
                                    $has = "has-warning";
                                } else {
                                    $has = "";
                                }
                                ?>
                                <div class="form-group <?php echo $has ?>">
                                    <label class="col-md-4 control-label">Label</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control input-inline input-medium" placeholder="Label de la side" name="<?php echo $this->addSideForm->get("shortlabel")->getName() ?>" value="<?php echo $this->addSideForm->get("shortlabel")->getValue() ?>">
                                        <?php if (count($this->addSideForm->get("shortlabel")) > 0): ?>
                                            <span class='help-inline'>
                                                <ul>
                                                    <?php foreach ($this->addSideForm->get("shortlabel")->getMessages() as $message): ?> 
                                                        <li>
                                                            <strong><?php echo $message ?></strong>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php
                                if (count($this->addSideForm->get("label")->getMessages()) > 0) {
                                    $has = "has-warning";
                                } else {
                                    $has = "";
                                }
                                ?>
                                <div class="form-group <?php echo $has ?>">
                                    <div class="row">
                                        <label class="col-md-4 control-label">Nom Complet</label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control input-inline input-medium" placeholder="Nom Complet de la Side" name="<?php echo $this->addSideForm->get("label")->getName() ?>" value="<?php echo $this->addSideForm->get("label")->getValue() ?>">
                                            <?php if (count($this->addSideForm->get("label")) > 0): ?>
                                                <span class='help-inline'>
                                                    <ul>
                                                        <?php foreach ($this->addSideForm->get("label")->getMessages() as $message): ?> 
                                                            <li>
                                                                <strong><?php echo $message ?></strong>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </span>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-5 col-md-2">
                                        <button type="submit" class="btn green">Créer</button>
                                        <a href='<?php echo $this->url("home_admin/common", array("controller" => "side", "action" => "list")) ?>' class="btn default">Annuler</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<!-- END CONTENT -->