<tr>
    <td>
        <table class="row note">
            <tr>
                <td class="wrapper last">
                    <h4>Merci d'avoir rejoins la Black Pony Company!</h4>
                    <p>
                        Cliquez sur le lien pour confirmer votre email et activer votre compte:
                    </p>
                    <!-- BEGIN: Note Panel -->
                    <table class="twelve columns" style="margin-bottom: 10px">
                        <tr>
                            <td class="panel">
                                <a href="http://projetx.nordri.fr/activate/<?php echo $this->Uer->getEmailvalidate() ?>">
                                    http://projetx.nordri.fr/activate/<?php echo $this->Uer->getEmailvalidate() ?> </a>
                            </td>
                            <td class="expander">
                            </td>
                        </tr>
                    </table>
                    <p>
                        Si vous cliquez sur l'url est que le lien ne fonctionne pas, copier-coller celui-ci dans votre navigateur.
                    </p>
                    <!-- END: Note Panel -->
                </td>
            </tr>
        </table>
    </td>
</tr>