<?php echo $this->doctype(); ?>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.1.3
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="fr" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="fr" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="fr">
    <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('BPC - ' . $this->translate('Black Pony Company'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>

        <meta content="Metronic Shop UI description" name="description">
        <meta content="Metronic Shop UI keywords" name="keywords">
        <meta content="keenthemes" name="author">
        <meta http-equiv="cleartype" content="on">

        <meta property="og:site_name" content="-CUSTOMER VALUE-">
        <meta property="og:title" content="-CUSTOMER VALUE-">
        <meta property="og:description" content="-CUSTOMER VALUE-">
        <meta property="og:type" content="website">
        <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
        <meta property="og:url" content="-CUSTOMER VALUE-">

        <!-- Le styles -->

        <link rel="shortcut icon" href="favicon.ico">

        <!-- Fonts START -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Pathway+Gothic+One|PT+Sans+Narrow:400+700|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css"> 
        <!-- Fonts END -->


        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/bootstrap/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/font-awesome/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/slider-revolution-slider/rs-plugin/css/settings.css')
                ->appendStylesheet($this->basePath() . '/assets/global/plugins/fancybox/source/jquery.fancybox.css')
                ->appendStylesheet($this->basePath() . '/assets/global/css/components.css')
                ->appendStylesheet($this->basePath() . '/assets/frontend/onepage/css/style.css')
                ->appendStylesheet($this->basePath() . '/assets/frontend/onepage/css/style-responsive.css')
                ->appendStylesheet($this->basePath() . '/assets/frontend/onepage/css/themes/blue.css')
                ->appendStylesheet($this->basePath() . '/assets/frontend/onepage/css/custom.css')
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>

        <!--[if lt IE 9]>
            <script src="<?php echo $this->basePath() ?>/assets/global/plugins/respond.min.js"></script>
        <![endif]-->

        <?php
        echo $this->inlineScript()
                ->appendFile($this->basePath() . '/assets/global/plugins/jquery-1.11.0.min.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/jquery-migrate-1.2.1.min.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/bootstrap/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.plugins.min.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.tools.min.js')
                ->appendFile($this->basePath() . '/assets/frontend/onepage/scripts/revo-ini.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/jquery.easing.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/jquery.parallax.js')
                ->appendFile($this->basePath() . '/assets/global/plugins/jquery.scrollTo.min.js')
                ->appendFile($this->basePath() . '/assets/frontend/onepage/scripts/jquery.nav.js')
                ->appendFile($this->basePath() . '/assets/frontend/onepage/scripts/layout.js')
                ->appendScript("
                    $(document).ready(function() {
                        Layout.init();
                    });
                ", "text/javascript");
        ?>
    </body>
</html>
