<!-- BEGIN LOGO -->
<div class="logo">
    <a class='btn btn-large btn-primary' href='<?php echo $this->url("home_inscription"); ?>'>Retour</a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="row">
    <div class="col-md-8 col-md-offset-2" style="background-color: #fff; padding: 30px; padding-top: 20px; padding-bottom: 15px;">

        <h1>Politique de confidentialité.</h1>
        <p><strong>Introduction</strong><br>
            Devant le développement des nouveaux outils de communication, il est nécessaire de porter une attention particulière à la protection de la vie privée. 
            C'est pourquoi, nous nous engageons à respecter la confidentialité des renseignements personnels que nous collectons.
        </p><hr>
        <h2>Collecte des renseignements personnels</h2>
        <p>
            Nous collectons les renseignements suivants : 
        </p>
        <ul>
            <li>Nom</li>
            <li>Prénom</li>
            <li>Adresse postale</li>
            <li>Code postal</li>
            <li>Adresse électronique</li>
            <li>Numéro de téléphone / télécopieur</li>
            <li>Âge / Date de naissance</li>
        </ul>

        <p>
            Les renseignements personnels que nous collectons sont recueillis au travers de formulaires et grâce à 
            l'interactivité établie entre vous et notre site Web.
            Nous utilisons également, comme indiqué dans la section suivante, des fichiers témoins et/ou journaux 
            pour réunir des informations vous concernant.
        </p><hr>
        <h2>Formulaires&nbsp; et interactivité:</h2>
        <p>
            Vos renseignements personnels sont collectés par le biais de formulaire, à savoir :
        </p>
        <ul>
            <li>Formulaire d'inscription au site Web</li>
            <li>Sondage d'opinion</li>
        </ul>
        <p>
            Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :
        </p>
        <ul>
            <li>Statistiques</li>
            <li>Contact</li>
            <li>Gestion du site Web (présentation, organisation)
            </li>
        </ul>
        <p>
            Vos renseignements sont également collectés par le biais de l'interactivité pouvant s'établir entre vous et notre site Web et ce, de la façon suivante:
        </p>	
        <ul>
        </ul>
        <p>
            Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :<br>
        </p>
        <ul>
        </ul>
        <hr>
        <h2>Fichiers journaux et témoins </h2>
        <p>
            Nous recueillons certaines informations par le biais de fichiers journaux (log file) et de fichiers témoins (cookies). Il s'agit principalement des informations suivantes :
        </p>
        <ul>
            <li>Adresse IP</li>
            <li>Heure et jour de connexion</li>
        </ul>

        <br>
        <p>
            Le recours à de tels fichiers nous permet : 
        </p>
        <ul>
            <li>Amélioration du service et accueil personnalisé</li>
            <li>Statistique</li>
        </ul><hr>
        <h2>Droit d'accès</h2>
        <p>
            Nous nous engageons à reconnaître un droit d'accès et de rectification aux personnes 
            concernées désireuses de consulter, modifier, voire radier les informations les concernant.<br>


            L'exercice de ce droit se fera :<br>
            Code postal : 7 et 9 rue Louise Hugues, Saint-Quentin 02100<br>	Courriel : victorien.vanroye@gmail.com<br>	Téléphone : 0698808450<br>	Section du site web : http://projetx.nordri.fr/<br>	</p><hr>
        <h2>Sécurité</h2>
        <p>

            Les renseignements personnels que nous collectons sont conservés 
            dans un environnement sécurisé. Les personnes travaillant pour nous sont tenues de respecter la confidentialité de vos informations.<br>
            Pour assurer la sécurité de vos renseignements personnels, nous avons recours aux mesures suivantes :
        </p>
        <ul>
            <li>Protocole SSL (Secure Sockets Layer)</li>
            <li>Gestion des accès - personne autorisée</li>
            <li>Gestion des accès - personne concernée</li>
            <li>Logiciel de surveillance du réseau</li>
            <li>Sauvegarde informatique</li>
            <li>Développement de certificat numérique</li>
            <li>Identifiant / mot de passe</li>
            <li>Pare-feu (Firewalls)</li>
        </ul>

        <p>
            Nous nous engageons à maintenir un haut degré de confidentialité en intégrant les dernières innovations technologiques permettant d'assurer 
            la confidentialité de vos transactions. Toutefois, comme aucun mécanisme n'offre une sécurité maximale, une part de risque est toujours présente 
            lorsque l'on utilise Internet pour transmettre des renseignements personnels. 
        </p>

    </div>
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->