<!-- BEGIN LOGO -->
<div class="logo">
    <a class='btn btn-large btn-primary' href='<?php echo $this->url("home_inscription"); ?>'>Retour</a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <div class="alert alert-success">
        <strong>Inscription Réussite</strong> <br/><span style="text-align: justify;">Vous allez recevoir un email avec un lien de confirmation. Cliquer sur celui-ci pour activer votre compte.</span> 
        <br/><a href="ts3server://ts.nordri.fr">Vous êtes invités à vous connecter sur le Teamspeak3 pour toutes questions.</a>
        <br/><br/><a href="http://www.teamspeak.com/?page=downloads">Lien de téléchargement de Teamspeak3.</a>
    </div>
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->