<!-- BEGIN LOGO -->
<div class="logo">
    <a class='btn btn-large btn-primary' href='<?php echo $this->url("home"); ?>'>Retour</a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <form class="login-form" action="<?php echo $this->url("home_login"); ?>" method="post">
        <h3 class="form-title">GameHub - Authentification</h3>
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            <span> Entrer un email et un password. </span>
        </div>
        <?php if (isset($this->form_login_messageErr)): ?>
            <div class="alert alert-danger">
                <strong>Erreur!</strong> <br/><?php echo $this->form_login_messageErr ?>
            </div>
        <?php endif; ?>
        <?php if (isset($this->form_login_messageWarn)): ?>
            <div class="alert alert-warning">
                <strong>Attention!</strong><br/> <?php echo $this->form_login_messageWarn ?>
            </div>
        <?php endif; ?>

        <?php
        if (count($this->form_login->getMessages("email")) > 0) {
            $emailW = "has-warning";
        } else {
            $emailW = "";
        }
        ?>
        <div class="form-group <?= $emailW ?>">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon <?= $emailW ?>">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="email" autocomplete="off" placeholder="Email" name="email"
                       <?php if (isset($this->form_login)): ?> value="<?php echo $this->form_login->get("email")->getValue() ?>"  <?php endif; ?>
                       />
            </div>
        </div>
        <?php
        if (count($this->form_login->getMessages("password")) > 0) {
            $passwordW = "has-warning";
        } else {
            $passwordW = "";
        }
        ?>
        <div class="form-group <?= $passwordW ?>">
            <label class="control-label visible-ie8 visible-ie9">Password</label>
            <div class="input-icon <?= $passwordW ?>">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"/>
            </div>
            <?php foreach ($this->form_login->getMessages("password") as $err): ?>
                <span class="help-block">
                    <?= $err ?>
                </span>
            <?php endforeach; ?>
        </div>

        <input type="hidden" name="<?php echo $this->form_login->get("token_csrf")->getName(); ?>" value="<?php echo $this->form_login->get("token_csrf")->getValue(); ?>" />
        <div class="form-actions">
            <label class="checkbox">
                <!--<input type="checkbox" name="remember" value="1"/> Remember me </label>-->
                <button type="submit" class="btn green pull-right">
                    Authentification <i class="m-icon-swapright m-icon-white"></i>
                </button>
        </div>
        <div class="forget-password">
            <h4>Password oublié ?</h4>
            <p>
                Pas d'inquiétude, cliquez <a href="javascript:;" id="forget-password">
                    ici </a>
                pour recréer un Mot de Passe.
            </p>
        </div>
        <div class="create-account">
            <p>
                Vous n'avez pas encore de compte ?&nbsp; <a class='btn btn-primary' href="javascript:;" id="register-btn">
                    Créer un compte </a>
            </p>
        </div>
    </form>
    <!-- END LOGIN FORM -->
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form class="forget-form" method="post">
        <h3>Forget Password ?</h3>
        <p>
            Enter your e-mail address below to reset your password.
        </p>
        <div class="form-group">
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="back-btn" class="btn">
                <i class="m-icon-swapleft"></i> Back </button>
            <button type="submit" class="btn green pull-right">
                Submit <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END FORGOT PASSWORD FORM -->
    <!-- BEGIN REGISTRATION FORM -->
    <form class="register-form" action="<?php echo $this->url("home_inscription"); ?>" method="post">

        <input type="hidden" name="<?php echo $this->form_inscription->get("token_csrf")->getName(); ?>" value="<?php echo $this->form_inscription->get("token_csrf")->getValue(); ?>" />
        <h3>Inscription</h3>
        <p>
            Entrez vos détails personnels:
        </p>

        <?php if (isset($this->form_inscription_messageErr) && !empty($this->form_inscription_messageErr)): ?>
            <div class="alert alert-error">
                <strong><?php echo $this->form_inscription_messageErr ?></strong>
            </div>
        <?php endif; ?>
        <?php if (isset($this->form_inscription_messageWarn) && !empty($this->form_inscription_messageWarn)): ?>
            <div class="alert alert-warning">
                <strong><?php echo $this->form_inscription_messageWarn ?></strong>
            </div>
        <?php endif; ?>
        <?php if (count($this->form_inscription->getMessages()) > 0): ?>
            <?php foreach ($this->form_inscription->getMessages() as $key => $message): ?> 
                <div class="alert alert-warning">
                    <strong> <?php echo $key ?></strong>
                    <strong><?php var_dump($message) ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="<?php echo $this->form_inscription->get("email")->getName(); ?>" value="<?php echo $this->form_inscription->get("email")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("email")) > 0): ?>
            <?php foreach ($this->form_inscription->get("email")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Nom</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Nom" name="<?php echo $this->form_inscription->get("nom")->getName(); ?>" value="<?php echo $this->form_inscription->get("nom")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("nom")) > 0): ?>
            <?php foreach ($this->form_inscription->get("nom")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Prénom</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Prénom" name="<?php echo $this->form_inscription->get("prenom")->getName(); ?>" value="<?php echo $this->form_inscription->get("prenom")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("prenom")) > 0): ?>
            <?php foreach ($this->form_inscription->get("prenom")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <div class="input-icon">
                <i class="fa fa-calendar"></i>
                <input style="width: 100%;" class="form-control date-picker" data-date-format="dd/mm/yyyy"  type="text" placeholder="Date de Naissance" value="<?php echo $this->form_inscription->get("datenai")->getValue(); ?>" name="<?php echo $this->form_inscription->get("datenai")->getName(); ?>" value="<?php echo $this->form_inscription->get("datenai")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("datenai")) > 0): ?>
            <?php foreach ($this->form_inscription->get("datenai")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Addresse (Facultatif)</label>
            <div class="input-icon">
                <i class="fa fa-check"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Address (Facultatif)" name="<?php echo $this->form_inscription->get("adresse")->getName(); ?>" value="<?php echo $this->form_inscription->get("adresse")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("adresse")) > 0): ?>
            <?php foreach ($this->form_inscription->get("adresse")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Ville (Facultatif)</label>
            <div class="input-icon">
                <i class="fa fa-location-arrow"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Ville (Facultatif)" name="<?php echo $this->form_inscription->get("ville")->getName(); ?>" value="<?php echo $this->form_inscription->get("ville")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("ville")) > 0): ?>
            <?php foreach ($this->form_inscription->get("ville")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Portable</label>
            <div class="input-icon">
                <i class="fa fa-phone"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Portable" name="<?php echo $this->form_inscription->get("portable")->getName(); ?>" value="<?php echo $this->form_inscription->get("portable")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("portable")) > 0): ?>
            <?php foreach ($this->form_inscription->get("portable")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Pays</label>
            <select name="<?php echo $this->form_inscription->get("pays")->getName(); ?>" id="select2_sample4" class="select2 form-control" value="<?php echo $this->form_inscription->get("pays")->getValue(); ?>">
                <option value=""></option>
                <option value="AF">Afghanistan</option>
                <option value="AL">Albania</option>
                <option value="DZ">Algeria</option>
                <option value="AS">American Samoa</option>
                <option value="AD">Andorra</option>
                <option value="AO">Angola</option>
                <option value="AI">Anguilla</option>
                <option value="AQ">Antarctica</option>
                <option value="AR">Argentina</option>
                <option value="AM">Armenia</option>
                <option value="AW">Aruba</option>
                <option value="AU">Australia</option>
                <option value="AT">Austria</option>
                <option value="AZ">Azerbaijan</option>
                <option value="BS">Bahamas</option>
                <option value="BH">Bahrain</option>
                <option value="BD">Bangladesh</option>
                <option value="BB">Barbados</option>
                <option value="BY">Belarus</option>
                <option value="BE">Belgium</option>
                <option value="BZ">Belize</option>
                <option value="BJ">Benin</option>
                <option value="BM">Bermuda</option>
                <option value="BT">Bhutan</option>
                <option value="BO">Bolivia</option>
                <option value="BA">Bosnia and Herzegowina</option>
                <option value="BW">Botswana</option>
                <option value="BV">Bouvet Island</option>
                <option value="BR">Brazil</option>
                <option value="IO">British Indian Ocean Territory</option>
                <option value="BN">Brunei Darussalam</option>
                <option value="BG">Bulgaria</option>
                <option value="BF">Burkina Faso</option>
                <option value="BI">Burundi</option>
                <option value="KH">Cambodia</option>
                <option value="CM">Cameroon</option>
                <option value="CA">Canada</option>
                <option value="CV">Cape Verde</option>
                <option value="KY">Cayman Islands</option>
                <option value="CF">Central African Republic</option>
                <option value="TD">Chad</option>
                <option value="CL">Chile</option>
                <option value="CN">China</option>
                <option value="CX">Christmas Island</option>
                <option value="CC">Cocos (Keeling) Islands</option>
                <option value="CO">Colombia</option>
                <option value="KM">Comoros</option>
                <option value="CG">Congo</option>
                <option value="CD">Congo, the Democratic Republic of the</option>
                <option value="CK">Cook Islands</option>
                <option value="CR">Costa Rica</option>
                <option value="CI">Cote d'Ivoire</option>
                <option value="HR">Croatia (Hrvatska)</option>
                <option value="CU">Cuba</option>
                <option value="CY">Cyprus</option>
                <option value="CZ">Czech Republic</option>
                <option value="DK">Denmark</option>
                <option value="DJ">Djibouti</option>
                <option value="DM">Dominica</option>
                <option value="DO">Dominican Republic</option>
                <option value="EC">Ecuador</option>
                <option value="EG">Egypt</option>
                <option value="SV">El Salvador</option>
                <option value="GQ">Equatorial Guinea</option>
                <option value="ER">Eritrea</option>
                <option value="EE">Estonia</option>
                <option value="ET">Ethiopia</option>
                <option value="FK">Falkland Islands (Malvinas)</option>
                <option value="FO">Faroe Islands</option>
                <option value="FJ">Fiji</option>
                <option value="FI">Finland</option>
                <option value="FR">France</option>
                <option value="GF">French Guiana</option>
                <option value="PF">French Polynesia</option>
                <option value="TF">French Southern Territories</option>
                <option value="GA">Gabon</option>
                <option value="GM">Gambia</option>
                <option value="GE">Georgia</option>
                <option value="DE">Germany</option>
                <option value="GH">Ghana</option>
                <option value="GI">Gibraltar</option>
                <option value="GR">Greece</option>
                <option value="GL">Greenland</option>
                <option value="GD">Grenada</option>
                <option value="GP">Guadeloupe</option>
                <option value="GU">Guam</option>
                <option value="GT">Guatemala</option>
                <option value="GN">Guinea</option>
                <option value="GW">Guinea-Bissau</option>
                <option value="GY">Guyana</option>
                <option value="HT">Haiti</option>
                <option value="HM">Heard and Mc Donald Islands</option>
                <option value="VA">Holy See (Vatican City State)</option>
                <option value="HN">Honduras</option>
                <option value="HK">Hong Kong</option>
                <option value="HU">Hungary</option>
                <option value="IS">Iceland</option>
                <option value="IN">India</option>
                <option value="ID">Indonesia</option>
                <option value="IR">Iran (Islamic Republic of)</option>
                <option value="IQ">Iraq</option>
                <option value="IE">Ireland</option>
                <option value="IL">Israel</option>
                <option value="IT">Italy</option>
                <option value="JM">Jamaica</option>
                <option value="JP">Japan</option>
                <option value="JO">Jordan</option>
                <option value="KZ">Kazakhstan</option>
                <option value="KE">Kenya</option>
                <option value="KI">Kiribati</option>
                <option value="KP">Korea, Democratic People's Republic of</option>
                <option value="KR">Korea, Republic of</option>
                <option value="KW">Kuwait</option>
                <option value="KG">Kyrgyzstan</option>
                <option value="LA">Lao People's Democratic Republic</option>
                <option value="LV">Latvia</option>
                <option value="LB">Lebanon</option>
                <option value="LS">Lesotho</option>
                <option value="LR">Liberia</option>
                <option value="LY">Libyan Arab Jamahiriya</option>
                <option value="LI">Liechtenstein</option>
                <option value="LT">Lithuania</option>
                <option value="LU">Luxembourg</option>
                <option value="MO">Macau</option>
                <option value="MK">Macedonia, The Former Yugoslav Republic of</option>
                <option value="MG">Madagascar</option>
                <option value="MW">Malawi</option>
                <option value="MY">Malaysia</option>
                <option value="MV">Maldives</option>
                <option value="ML">Mali</option>
                <option value="MT">Malta</option>
                <option value="MH">Marshall Islands</option>
                <option value="MQ">Martinique</option>
                <option value="MR">Mauritania</option>
                <option value="MU">Mauritius</option>
                <option value="YT">Mayotte</option>
                <option value="MX">Mexico</option>
                <option value="FM">Micronesia, Federated States of</option>
                <option value="MD">Moldova, Republic of</option>
                <option value="MC">Monaco</option>
                <option value="MN">Mongolia</option>
                <option value="MS">Montserrat</option>
                <option value="MA">Morocco</option>
                <option value="MZ">Mozambique</option>
                <option value="MM">Myanmar</option>
                <option value="NA">Namibia</option>
                <option value="NR">Nauru</option>
                <option value="NP">Nepal</option>
                <option value="NL">Netherlands</option>
                <option value="AN">Netherlands Antilles</option>
                <option value="NC">New Caledonia</option>
                <option value="NZ">New Zealand</option>
                <option value="NI">Nicaragua</option>
                <option value="NE">Niger</option>
                <option value="NG">Nigeria</option>
                <option value="NU">Niue</option>
                <option value="NF">Norfolk Island</option>
                <option value="MP">Northern Mariana Islands</option>
                <option value="NO">Norway</option>
                <option value="OM">Oman</option>
                <option value="PK">Pakistan</option>
                <option value="PW">Palau</option>
                <option value="PA">Panama</option>
                <option value="PG">Papua New Guinea</option>
                <option value="PY">Paraguay</option>
                <option value="PE">Peru</option>
                <option value="PH">Philippines</option>
                <option value="PN">Pitcairn</option>
                <option value="PL">Poland</option>
                <option value="PT">Portugal</option>
                <option value="PR">Puerto Rico</option>
                <option value="QA">Qatar</option>
                <option value="RE">Reunion</option>
                <option value="RO">Romania</option>
                <option value="RU">Russian Federation</option>
                <option value="RW">Rwanda</option>
                <option value="KN">Saint Kitts and Nevis</option>
                <option value="LC">Saint LUCIA</option>
                <option value="VC">Saint Vincent and the Grenadines</option>
                <option value="WS">Samoa</option>
                <option value="SM">San Marino</option>
                <option value="ST">Sao Tome and Principe</option>
                <option value="SA">Saudi Arabia</option>
                <option value="SN">Senegal</option>
                <option value="SC">Seychelles</option>
                <option value="SL">Sierra Leone</option>
                <option value="SG">Singapore</option>
                <option value="SK">Slovakia (Slovak Republic)</option>
                <option value="SI">Slovenia</option>
                <option value="SB">Solomon Islands</option>
                <option value="SO">Somalia</option>
                <option value="ZA">South Africa</option>
                <option value="GS">South Georgia and the South Sandwich Islands</option>
                <option value="ES">Spain</option>
                <option value="LK">Sri Lanka</option>
                <option value="SH">St. Helena</option>
                <option value="PM">St. Pierre and Miquelon</option>
                <option value="SD">Sudan</option>
                <option value="SR">Suriname</option>
                <option value="SJ">Svalbard and Jan Mayen Islands</option>
                <option value="SZ">Swaziland</option>
                <option value="SE">Sweden</option>
                <option value="CH">Switzerland</option>
                <option value="SY">Syrian Arab Republic</option>
                <option value="TW">Taiwan, Province of China</option>
                <option value="TJ">Tajikistan</option>
                <option value="TZ">Tanzania, United Republic of</option>
                <option value="TH">Thailand</option>
                <option value="TG">Togo</option>
                <option value="TK">Tokelau</option>
                <option value="TO">Tonga</option>
                <option value="TT">Trinidad and Tobago</option>
                <option value="TN">Tunisia</option>
                <option value="TR">Turkey</option>
                <option value="TM">Turkmenistan</option>
                <option value="TC">Turks and Caicos Islands</option>
                <option value="TV">Tuvalu</option>
                <option value="UG">Uganda</option>
                <option value="UA">Ukraine</option>
                <option value="AE">United Arab Emirates</option>
                <option value="GB">United Kingdom</option>
                <option value="US">United States</option>
                <option value="UM">United States Minor Outlying Islands</option>
                <option value="UY">Uruguay</option>
                <option value="UZ">Uzbekistan</option>
                <option value="VU">Vanuatu</option>
                <option value="VE">Venezuela</option>
                <option value="VN">Viet Nam</option>
                <option value="VG">Virgin Islands (British)</option>
                <option value="VI">Virgin Islands (U.S.)</option>
                <option value="WF">Wallis and Futuna Islands</option>
                <option value="EH">Western Sahara</option>
                <option value="YE">Yemen</option>
                <option value="ZM">Zambia</option>
                <option value="ZW">Zimbabwe</option>
            </select>
        </div>
        <?php if (count($this->form_inscription->get("pays")) > 0): ?>
            <?php foreach ($this->form_inscription->get("pays")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <p>
            Entrer vos détails de compte:
        </p>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Username</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="<?php echo $this->form_inscription->get("username")->getName(); ?>" value="<?php echo $this->form_inscription->get("username")->getValue(); ?>"/>
            </div>
        </div>
        <?php if (count($this->form_inscription->get("username")) > 0): ?>
            <?php foreach ($this->form_inscription->get("username")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Mot de Passe</label>
            <div class="input-icon">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="<?php echo $this->form_inscription->get("passwd0")->getName(); ?>" />
            </div>
        </div>
        <?php if (count($this->form_inscription->get("passwd0")) > 0): ?>
            <?php foreach ($this->form_inscription->get("passwd0")->getMessages() as $message): ?> 
                <div class="alert alert-warning">
                    <strong><?php echo $message ?></strong>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Re-taper votre Mot de Passe</label>
            <div class="controls">
                <div class="input-icon">
                    <i class="fa fa-check"></i>
                    <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="<?php echo $this->form_inscription->get("passwd1")->getName(); ?>"/>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>
                <input type="checkbox" name="<?php echo $this->form_inscription->get("rights")->getName(); ?>"/> J'accepte  <a href="<?php echo $this->url("home_condutil") ?>">
                    les Conditions d'Utilisation </a>
                et <a href="<?php echo $this->url("home_confpol") ?>">
                    les politiques de Confidentialité. </a>
            </label>
            <div id="register_tnc_error">
            </div>
        </div>
        <div class="form-actions">
            <button id="register-back-btn" type="button" class="btn">
                <i class="m-icon-swapleft"></i> Retour </button>
            <button type="submit" id="register-submit-btn" class="btn green pull-right">
                Inscription <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END REGISTRATION FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->