<!-- BEGIN LOGO -->
<div class="logo">
    <a class='btn btn-large btn-primary' href='<?php echo $this->url("home_login"); ?>'>Retour</a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <span style="text-align: center">
        <h2>Vous n'êtes pas autorisé à accéder à cette partie.
            Pour plus de renseignement, rendez-vous sur</h2> <br/>
        <div style="margin: 0 auto">
            <a class="btn btn-large btn-primary" href='http://forum.nordri.fr'>le forum </a> - <a class="btn btn-large btn-info" href="teamspeak3://ts.nordri.fr">le Teamspeak3 </a>
        </div>
    </span>
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->