
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content" style="min-height:1269px">
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            Première Connection <small>Page de présentation</small>
        </h3>
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="<?php echo $this->url("home_connected") ?>">Home</a>
                </li>
            </ul>
            <div class="page-toolbar">
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN Portlet PORTLET-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-energy"></i>
                            <span class="caption-subject bold uppercase">Etape 01 : Installation du Mode de Jeu</span>
                            <span class="caption-helper">Explication</span>
                        </div>
                        <div class="actions">
                            <a href="#" class="btn btn-circle btn-info">
                                <i class="fa fa-download"></i> Télécharger le Launcher </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="scroller" style="height:200px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                            <h4>Explication de pourquoi un Launcher ?</h4>
                            <p>
                                La nécessité par rapport au mod.
                            </p>
                            <p>
                                L'ajout de fonctionnalité grâce au launcher.
                            </p>
                        </div>
                    </div>
                </div>
                <!-- END Portlet PORTLET-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN Portlet PORTLET-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-plus"></i>
                            <span class="caption-subject bold uppercase"> Etape 02 : Création du premier Personnage</span>
                            <span class="caption-helper">Explication</span>
                        </div>
                        <div class="actions">
                            <a href="<?php echo $this->url("home_connected",array("controller"=>"personnage")) ?>" class="btn btn-circle btn-primary">
                                <i class="fa fa-link"></i> Créer son premier Personnage </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="scroller" style="height:150px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                            <h4>Explication du mode de jeu et de son fonctionnement.</h4>
                            <p>
                                Une vie.<br/>
                                - éviter de mourir.<br/>
                                - un patrimoine à construire.<br/>
                            </p><br/>
                            <p>
                                Un Patrimoine à sauvegarder.<br/>
                                - Assurer son Patrimoine.<br/>
                                - Assurer que ses biens seront légués.
                            </p>
                            <p>
                                Choix de la région pour l'immigration.
                            </p>
                        </div>
                    </div>
                </div>
                <!-- END Portlet PORTLET-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN Portlet PORTLET-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-control-play"></i>
                            <span class="caption-subject bold uppercase">Etape 03 : Premier </span>
                            <span class="caption-helper">Explication</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="scroller" style="height:200px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                            <h4>Explication de pourquoi un Launcher ?</h4>
                            <p>
                                La nécessité par rapport au mod.
                            </p>
                            <p>
                                L'ajout de fonctionnalité grâce au launcher.
                            </p>
                        </div>
                    </div>
                </div>
                <!-- END Portlet PORTLET-->
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<!-- END CONTENT -->