<!-- BEGIN INBOX DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <i class="icon-envelope-open"></i>
        <span class="badge badge-primary">
            4 </span>
    </a>
    <ul class="dropdown-menu">
        <li>
            <p>
                You have 12 new messages
            </p>
        </li>
        <li>
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><ul class="dropdown-menu-list scroller" style="overflow: hidden; width: auto; height: 250px;" data-initialized="1">
                    <li>
                        <a href="inbox.html?a=view">
                            <span class="photo">
                                <img src="../../assets/admin/layout2/img/avatar2.jpg" alt="">
                            </span>
                            <span class="subject">
                                <span class="from">
                                    Lisa Wong </span>
                                <span class="time">
                                    Just Now </span>
                            </span>
                            <span class="message">
                                Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                        </a>
                    </li>
                    <li>
                        <a href="inbox.html?a=view">
                            <span class="photo">
                                <img src="../../assets/admin/layout2/img/avatar3.jpg" alt="">
                            </span>
                            <span class="subject">
                                <span class="from">
                                    Richard Doe </span>
                                <span class="time">
                                    16 mins </span>
                            </span>
                            <span class="message">
                                Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                        </a>
                    </li>
                    <li>
                        <a href="inbox.html?a=view">
                            <span class="photo">
                                <img src="../../assets/admin/layout2/img/avatar1.jpg" alt="">
                            </span>
                            <span class="subject">
                                <span class="from">
                                    Bob Nilson </span>
                                <span class="time">
                                    2 hrs </span>
                            </span>
                            <span class="message">
                                Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                        </a>
                    </li>
                    <li>
                        <a href="inbox.html?a=view">
                            <span class="photo">
                                <img src="../../assets/admin/layout2/img/avatar2.jpg" alt="">
                            </span>
                            <span class="subject">
                                <span class="from">
                                    Lisa Wong </span>
                                <span class="time">
                                    40 mins </span>
                            </span>
                            <span class="message">
                                Vivamus sed auctor 40% nibh congue nibh... </span>
                        </a>
                    </li>
                    <li>
                        <a href="inbox.html?a=view">
                            <span class="photo">
                                <img src="../../assets/admin/layout2/img/avatar3.jpg" alt="">
                            </span>
                            <span class="subject">
                                <span class="from">
                                    Richard Doe </span>
                                <span class="time">
                                    46 mins </span>
                            </span>
                            <span class="message">
                                Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                        </a>
                    </li>
                </ul><div class="slimScrollBar" style="width: 7px; position: absolute; top: 0px; opacity: 0.4; border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px; z-index: 99; right: 1px; display: block; background: rgb(187, 187, 187);"></div><div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(234, 234, 234);"></div></div>
        </li>
        <li class="external">
            <a href="inbox.html">
                See all messages <i class="icon-arrow-right"></i>
            </a>
        </li>
    </ul>
</li>
<!-- END INBOX DROPDOWN -->