<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown dropdown-user">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <?php
        $settings = array(
            'img_size' => 40,
            'default_img' => \Zend\View\Helper\Gravatar::DEFAULT_MM,
            'rating' => \Zend\View\Helper\Gravatar::RATING_G,
            'secure' => null,
        );
        $attr = array(
            'class' => 'img-circle hide1',
            'alt' => ""
        );
        echo $this->gravatar($this->identity->getEmail(), $settings, $attr);
        ?>
        <span class="username username-hide-on-mobile">
            <?php echo $this->identity->getUsername() ?> </span>
        <i class="fa fa-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="<?php echo $this->url("home_connected", array("controller" => "user", "action" => "profil")) ?>">
                <i class="icon-user"></i> Mon Profil</a>
        </li>
        <li class="divider">
        </li>
        <li>
            <a href="<?php echo $this->url("home_logout") ?>">
                <i class="icon-key"></i> Déconnexion</a>
        </li>
    </ul>
</li>
<!-- END USER LOGIN DROPDOWN -->