<!-- BEGIN TODO DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <i class="icon-calendar"></i>
        <span class="badge badge-success">
            3 </span>
    </a>
    <ul class="dropdown-menu extended tasks">
        <li>
            <p>
                You have 12 pending tasks
            </p>
        </li>
        <li>
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><ul class="dropdown-menu-list scroller" style="overflow: hidden; width: auto; height: 250px;" data-initialized="1">
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    New release v1.2 </span>
                                <span class="percent">
                                    30% </span>
                            </span>
                            <div class="progress">
                                <div style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        40% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    Application deployment </span>
                                <span class="percent">
                                    65% </span>
                            </span>
                            <div class="progress progress-striped">
                                <div style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        65% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    Mobile app release </span>
                                <span class="percent">
                                    98% </span>
                            </span>
                            <div class="progress">
                                <div style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        98% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    Database migration </span>
                                <span class="percent">
                                    10% </span>
                            </span>
                            <div class="progress progress-striped">
                                <div style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        10% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    Web server upgrade </span>
                                <span class="percent">
                                    58% </span>
                            </span>
                            <div class="progress progress-striped">
                                <div style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        58% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    Mobile development </span>
                                <span class="percent">
                                    85% </span>
                            </span>
                            <div class="progress progress-striped">
                                <div style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        85% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="page_todo.html">
                            <span class="task">
                                <span class="desc">
                                    New UI release </span>
                                <span class="percent">
                                    18% </span>
                            </span>
                            <div class="progress progress-striped">
                                <div style="width: 18%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
                                    <div class="sr-only">
                                        18% Complete
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul><div class="slimScrollBar" style="width: 7px; position: absolute; top: 0px; opacity: 0.4; border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px; z-index: 99; right: 1px; display: block; background: rgb(187, 187, 187);"></div><div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(234, 234, 234);"></div></div>
        </li>
        <li class="external">
            <a href="page_todo.html">
                See all tasks <i class="icon-arrow-right"></i>
            </a>
        </li>
    </ul>
</li>
<!-- END TODO DROPDOWN -->