<!-- Header BEGIN -->
<div class="header header-mobi-ext">
    <div class="container">
        <div class="row">
            <!-- Logo BEGIN -->
            <div class="col-md-2 col-sm-2">
                <a class="scroll site-logo" href="#promo-block"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/logo/blue.png" alt="Metronic One Page"></a>
            </div>
            <!-- Logo END -->

            <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

            <!-- Navigation BEGIN -->
            <div class="col-md-10 pull-right">
                <ul class="header-navigation">
                    <li class="current"><a href="">H</a></li>
                    <li><a href="#about">Description</a></li>
                    <li><a href="#services">Aperçu</a></li>
                    <li><a href="#team">BPC</a></li>
                    <li><a href="#portfolio">Screen</a></li>
                    <li><a href="#benefits">Benefits</a></li>            
                    <li><a href="http://forum.bpca3.local">Forum</a></li>
                    <li><a href="<?php echo $this->url("home_connected") ?>">GameHub</a></li>
                </ul>
            </div>
            <!-- Navigation END -->
        </div>
    </div>
</div>
<!-- Header END -->

<!-- Promo block BEGIN -->
<div class="promo-block" id="promo-block">
    <div class="tp-banner-container">
        <div class="tp-banner" >
            <ul>
                <li data-transition="fade" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-1">
                    <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/slide1.jpg" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                    <div class="tp-caption large_text customin customout start"
                         data-x="center"
                         data-hoffset="0"
                         data-y="center"
                         data-voffset="60"
                         data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="1000"
                         data-start="500"
                         data-easing="Back.easeInOut"
                         data-endspeed="300">
                        <div class="promo-like"><i class="fa fa-thumbs-up"></i></div>
                        <div class="promo-like-text">
                            <h2>Let's just do it</h2>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing<br> elit amet sed diam nonummy nibh <a href="javascript:void(0);">dolore</a></p>
                        </div>
                    </div>
                    <div class="tp-caption large_bold_white fade"
                         data-x="center"
                         data-y="center"
                         data-voffset="-110"
                         data-speed="300"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="500"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">Parallax <span>One Page</span> Has Arrived
                    </div>
                </li>
                <li data-transition="fadefromright" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-2">
                    <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_bg.jpg" alt="slidebg2" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                    <div class="caption lft start"
                         data-y="center"
                         data-voffset="40"
                         data-x="center"
                         data-hoffset="-250"
                         data-speed="600" 
                         data-start="500" 
                         data-easing="easeOutBack"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_iphone_left.png" alt="">
                    </div>
                    <div class="caption lft start"
                         data-y="center"
                         data-voffset="130"
                         data-x="center"
                         data-hoffset="170"
                         data-speed="600" 
                         data-start="1200" 
                         data-easing="easeOutBack"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_iphone_right.png" alt="">
                    </div>
                    <div class="tp-caption large_bold_white fade"
                         data-x="center"
                         data-y="40"
                         data-speed="300"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="500"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">Extremely <span>Responsive</span> Design
                    </div>
                </li>
                <li data-transition="fade" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-3">

                    <div class="tp-caption tp-fade fadeout fullscreenvideo"
                         data-x="0"
                         data-y="0"
                         data-speed="1000"
                         data-start="1100"
                         data-easing="Power4.easeOut"
                         data-endspeed="1500"
                         data-endeasing="Power4.easeIn"
                         data-autoplay="true"
                         data-autoplayonlyfirsttime="false"
                         data-nextslideatend="true"
                         data-forceCover="1"
                         data-dottedoverlay="twoxtwo"
                         data-aspectratio="16:9"
                         data-forcerewind="on"
                         style="z-index: 2">

                        <video class="video-js vjs-default-skin" preload="none" width="100%" height="100%">
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.mp4' type='video/mp4'>
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.webm' type='video/webm'>
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.ogv' type='video/ogg'>
                        </video>
                    </div>

                    <div class="tp-caption large_bold_white_25 customin customout tp-resizeme"
                         data-x="center" data-hoffset="0"
                         data-y="170"
                         data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="600"
                         data-start="1400"
                         data-easing="Power4.easeOut"
                         data-endspeed="600"
                         data-endeasing="Power0.easeIn"
                         style="z-index: 3">The clearest way into the Universe<br/>is through a forest wilderness.
                    </div>

                    <div class="tp-caption medium_text_shadow customin customout tp-resizeme"
                         data-x="center" data-hoffset="0"
                         data-y="bottom" data-voffset="-140"
                         data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="600"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="600"
                         data-endeasing="Power0.easeIn"
                         style="z-index: 4">John Muir
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Promo block END -->

<!-- About block BEGIN -->
<div class="about-block content content-center" id="about">
    <div class="container">
        <h2><strong>Black Pony Compony</strong> présente</h2>
        <h4>un nouveau mode de jeu sur Arma III</h4>

        <div class="ab-trio">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/trio.png" alt="" class="img-responsive">
            <div class="ab-cirlce ab-cirle-blue">
                <i class="fa fa-code"></i>
                <strong>Fonctionnalités Uniques</strong>
            </div>
            <div class="ab-cirlce ab-cirle-red">
                <i class="fa fa-gift"></i>
                <strong>Immersion Compléte</strong>
            </div>
            <div class="ab-cirlce ab-cirle-green">
                <i class="fa fa-mobile"></i>
                <strong>Responsive</strong>
            </div>
        </div>
    </div>
</div>
<!-- About block END -->

<!-- Services block BEGIN -->
<div class="services-block content content-center" id="services">
    <div class="container">
        <h2><strong>Aperçu</strong> des fonctionnalités</h2>
        <h6>Cette liste ne présente qu'une petite partie de l'environnement du mod.</h6>

        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-12 item">
                <i class="fa fa-heart"></i>
                <h3>Réelle incarnation</h3>
                <p>Vous arrivez comme un immigrant<br> avec un nouveau nom qui vous définira</p>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 item">
                <i class="fa fa-mobile"></i>
                <h3>Le navigateur s'allie au Jeu</h3>
                <p>Vous aurez à des controls depuis <br> navigateur sur ordinateur ou téléphone</p>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 item">
                <i class="fa fa-signal"></i>
                <h3>Liberté du Marché</h3>
                <p>Faite du transport de marchandise pour alimenter un marché<br> ou construiser une puissante industrie.</p>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 item">
                <i class="fa fa-camera"></i>
                <h3>Multi-Island</h3>
                <p>Prenez l'avion pour vous rendre dans d'autre pays<br> attention à la géopolitique de chaque pays.</p>
            </div>
        </div>
    </div>
</div>
<!-- Services block END -->

<!-- Message block BEGIN -->
<div class="message-block content content-center valign-center" id="message-block">
    <div class="valign-center-elem">
        <h2>Ne pensez plus comme avant <strong>Vous incarnez une vie réelle.</strong></h2>
        <em>Eviter ou Chasser le danger !</em>
    </div>
</div>
<!-- Message block END -->

<!-- Team block BEGIN -->
<div class="team-block content content-center margin-bottom-40" id="team">
    <div class="container">
        <h2>BPC - <strong>L'équipe</strong></h2>
        <h4>La BPC ne se limite pas au développerment</h4>

        <div class="row">
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/img/2ad54834.jpg" alt="Marcus Doe" class="img-responsive">
                <h3>MirageCentury</h3>
                <em>Dev / Administrateur</em>
                <p>RP : <strong>Mirage Century</strong> : Général des Forces Militaires de Régulation</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                </div>
            </div>
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/people/img7-large.jpg" alt="Elena Taylor" class="img-responsive">
                <h3>Varial</h3>
                <em>Dev-Oxygen / Administrateur</em>
                <p>RP : <strong>Varial XXXXX</strong> : Général des Forces Militaires de Régulation chargé des affaires civils</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-facebook"></a>
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                    <a href="javascript:void(0);" class="fa fa-google-plus"></a>
                </div>
            </div>
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/people/img8-large.jpg" alt="Cris Nilson" class="img-responsive">
                <h3>Bourrechs</h3>
                <em>Dev / Administrateur</em>
                <p>RP : <strong>Bou Bou</strong> : Général des Forces Militaires de Régulation chargé des opérations aériennes</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-facebook"></a>
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                    <a href="javascript:void(0);" class="fa fa-google-plus"></a>
                </div>
            </div>
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/people/img8-large.jpg" alt="Cris Nilson" class="img-responsive">
                <h3>Tristounet</h3>
                <em>Administrateur</em>
                <p>RP : <strong>Tristounet XXXX</strong> : Colonnel des Forces Militaires de Régulation chargé des relations et formations avec les armées locales</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-facebook"></a>
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                    <a href="javascript:void(0);" class="fa fa-google-plus"></a>
                </div>
            </div>
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/people/img8-large.jpg" alt="Cris Nilson" class="img-responsive">
                <h3>Gwadakila</h3>
                <em> Soldat </em>
                <p>RP : <strong> Gwada Kila </strong> : Lieutenant des Forces Militaires de Régulation chargé des transferts de ressource</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-facebook"></a>
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                    <a href="javascript:void(0);" class="fa fa-google-plus"></a>
                </div>
            </div>
            <div class="col-md-2 item">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/people/img8-large.jpg" alt="Cris Nilson" class="img-responsive">
                <h3>Titus</h3>
                <em>Soldat</em>
                <p>RP : <strong>Titus XXXX</strong> : Lieutenant des Forces Militaires de Régulation adjoint du Général Tristounet pour la formations des armées locales</p>
                <div class="tb-socio">
                    <a href="javascript:void(0);" class="fa fa-facebook"></a>
                    <a href="javascript:void(0);" class="fa fa-twitter"></a>
                    <a href="javascript:void(0);" class="fa fa-google-plus"></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Team block END -->

<!-- Portfolio block BEGIN -->
<div class="portfolio-block content content-center" id="portfolio">
    <div class="container">
        <h2 class="margin-bottom-50">Dernière <strong>Images</strong></h2>
    </div>
    <div class="row">
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/2.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/2.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/6.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/6.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/8.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/8.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/3.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/3.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/5.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/5.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/4.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/4.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/1.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/1.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/10.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/10.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/9.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/9.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/7.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/7.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/2.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/2.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
        <div class="item col-md-2 col-sm-6 col-xs-12">
            <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/8.jpg" alt="NAME" class="img-responsive">
            <a href="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/portfolio/8.jpg" class="zoom valign-center">
                <div class="valign-center-elem">
                    <strong>London City Project</strong>
                    <em>Property</em>
                    <b>Details</b>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- Portfolio block END -->

<!-- Choose us block BEGIN -->
<div class="choose-us-block content text-center margin-bottom-40" id="benefits">
    <div class="container">
        <h2>Pourquoi <strong>nous choisir</strong> ?</h2>
        <h4>Voici quelque points qui vous ferons prendre un avis.</h4>

        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12 text-left">
                <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/choose-us.png" alt="Why to choose us" class="img-responsive">
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 text-left">
                <div class="panel-group" id="accordion1">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_1">Un filtrage et un suivi des joueurs très poussé</a>
                            </h5>
                        </div>
                        <div id="accordion1_1" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>Dès le début nous trions les joueurs par rapport à leur envie de nous rejoindre mais aussi pour leur sérieux.</p>
                                <p>Mais ce n'est pas fini, en jeu des éléments mesurent et détermine si un joueur fait des actions répréhensibles avertissant nos administrateurs et modérateurs afin soit de rappeler à l'ordre soit de sanctionner.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_2">Une dynamicité et une immersion totale</a>
                            </h5>
                        </div>
                        <div id="accordion1_2" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Le début sur les pays sera dificile pour les premiers arrivant mais cela sera un beau challange sachant que ceux sont les joueurs qui crée les activités commerciales mais aussi les missions pour les différentes fastions.</p>
                                <p>Tous est donc dans les mains des joueurs à eux de s'associer pour créer des pays très puissant mais cela peut tourner vers bien d'autre route. C'est pour cela qu'il existe en plus des forces locales une armée extérieur qui s'occupe de rééquilibré la balance autant par
                                    des actions armées que par de l'humanitaire.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_3">Une vie est une vie</a>
                            </h5>
                        </div>
                        <div id="accordion1_3" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Lorsque vous arriverez, l'immigration vous fera vos papiers et vous expliquera les régles du pays sur lequel vous arrivez. Faite attention toutes les propriétés ne vous appartiennent pas mais appartiennent à votre personnage. En cas de décès faite bien en sorte que vous récupériez le plus possible de vso biens via votre testaments.</p>
                                <p>Faite très attention à vous quand vous faites des actions répréhensibles, vos empreintes peuvent rester sur le lieu de vos délits mais aussi bien d'autre trace. Les forces d'investigations seront à vos trousses et construieront des rapports d'accusations avec ces preuves.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_4">Des ressources, des industries, du commerce</a>
                            </h5>
                        </div>
                        <div id="accordion1_4" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Beaucoup de ressource existe sur tous les pays mais à l'état naturel, exploité par des industries d'état ou non. C'est à vous de faire évoluer ces points afin de récupérer de plus en plus de ressource rapidement pour vos industries ou pour la revente.</p>
                                <p>Tous dois être fabriquer ou importer. Les marchands peuvent se retrouver à court de produit si personne ne les approvisionne à vous de faire des bénéfices.</p>
                                <p>Vous pourrez créer des points de ventes, des industries, des points d'extraction mais aussi des hangars pour stocker les ressources.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_5">Des contrats ou des Missions </a>
                            </h5>
                        </div>
                        <div id="accordion1_5" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Chaque faction aura ces types de missions qui pourront être proposer autant par les joueurs que par les administrateurs car rien ne se fera par magie. S'il faut ravitailler un village avec un convoit humanitaire, il faudra des camions civils au militaire des forces de régulation pour aider à transporter des marchandises. Et vous serez toujours rémunérer pour vos tâches accomplies.</p>
                                <p>Les missions seront là pour réguler l'activité dans les pays mais aussi créer une certaine dynamique qui peut être difficile à atteindre dans des mods de jeu standart.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_6">Les forces locales et de régulation</a>
                            </h5>
                        </div>
                        <div id="accordion1_6" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Les forces locales sont attachés à la région, elles sont autant les militaires et la police du pays. Hierarchisé, ils soutiennent la population et applique un certain ordre permettant à chaque de vivre correctement. </p>
                                <p>Les forces de régulation, venu d'un pays extérieur puissant assure un soutien stratégique au force locale, il forme aussi celle-ci afin qu'elle atteigne une opérationnalité exceptionnelle. Elle amèe aussi des ressources vitales si celle-ci manque, nourriture, eau et argent.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Choose us block END -->

<!-- Checkout block BEGIN -->
<div class="checkout-block content">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>Bientôt rejoingez la Alpha <em> Informations sur Twitter </em></h2>
            </div>
            <div class="col-md-2 text-right">
                <a href="#" target="_blank" class="btn btn-warning disabled">ALPHA</a>
            </div>
            <div class="col-md-2 text-right">
                <a href="#" target="_blank" class="btn btn-primary disabled">BETA</a>
            </div>
        </div>
    </div>
</div>
<!-- Checkout block END -->

<!-- Facts block BEGIN -->
<div class="facts-block content content-center" id="facts-block">
    <h2>Quelques chiffres ...</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="item">
                    <strong>2/0</strong>
                    Admin / Modo
                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="item">
                    <strong>0</strong>
                    Pays
                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="item">
                    <strong>0</strong>
                    Joueurs
                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="item">
                    <strong>0</strong>
                    Personnages
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Facts block END -->

<!-- Testimonials block BEGIN -->
<div class="testimonials-block content content-center margin-bottom-65">
    <div class="container">
        <h2>Customer <strong>testimonials</strong></h2>
        <h4>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</h4>

        <div class="carousel slide" data-ride="carousel" id="testimonials-block">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <!-- Carousel items -->
                <div class="active item">
                    <blockquote><p>This is the most awesome, full featured, easy, costomizeble theme. It’s extremely responsive and very helpful to all suggestions.</p></blockquote>
                    <span class="testimonials-name">Mark Doe</span>
                </div>
                <!-- Carousel items -->
                <div class="item">
                    <blockquote><p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse.</p></blockquote>
                    <span class="testimonials-name">Joe Smith</span>
                </div>
                <!-- Carousel items -->
                <div class="item">
                    <blockquote><p>Williamsburg carles vegan helvetica. Cosby sweater eu banh mi, qui irure terry richardson ex squid Aliquip placeat salvia cillum iphone.</p></blockquote>
                    <span class="testimonials-name">Linda Adams</span>
                </div>
            </div>
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#testimonials-block" data-slide-to="0" class="active"></li>
                <li data-target="#testimonials-block" data-slide-to="1"></li>
                <li data-target="#testimonials-block" data-slide-to="2"></li>
            </ol>
        </div>
    </div>
</div>
<!-- Testimonials block END -->

<!-- Partners block BEGIN -->
<div class="partners-block">
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-3 col-xs-6">
                <img style="height: 106px;" src="<?php echo $this->basePath() ?>/img/logo_php.png" alt="php">
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <img style="height: 84px; margin-top: 11px;" src="<?php echo $this->basePath() ?>/img/zf2-logo-mark.png" alt="zend framework 2">
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <img style="height: 94px; margin-top: 6px;" src="<?php echo $this->basePath() ?>/img/360px-Bohemiawhite.png" alt="zend framework 2">
            </div>
        </div>
    </div>
</div>
<!-- Partners block END -->

<!-- BEGIN PRE-FOOTER -->
<div class="pre-footer" id="contact">
    <div class="container">
        <div class="row">
            <!-- BEGIN BOTTOM ABOUT BLOCK -->
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2>About us</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna aliquarm erat sit volutpat. Nostrud exerci tation ullamcorper suscipit lobortis nisl aliquip  commodo consequat. </p>
                <p>Duis autem vel eum iriure dolor vulputate velit esse molestie at dolore.</p>
            </div>
            <!-- END BOTTOM ABOUT BLOCK -->

            <!-- BEGIN TWITTER BLOCK --> 
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2 class="margin-bottom-0">Latest Tweets</h2>
                <a class="twitter-timeline" href="https://twitter.com/twitterapi" data-tweet-limit="2" data-theme="dark" data-link-color="#57C8EB" data-widget-id="455411516829736961" data-chrome="noheader nofooter noscrollbar noborders transparent">Loading tweets by @keenthemes...</a>      
            </div>
            <!-- END TWITTER BLOCK -->

            <div class="col-md-4 col-sm-6 pre-footer-col">
                <!-- BEGIN BOTTOM CONTACTS -->
                <!-- END BOTTOM CONTACTS -->

                <!--                <div class="pre-footer-subscribe-box">
                                    <h2>Newsletter</h2>
                                    <form action="javascript:void(0);">
                                        <div class="input-group">
                                            <input type="text" placeholder="youremail@mail.com" class="form-control">
                                            <span class="input-group-btn">
                                                <button class="btn btn-primary" type="submit">Subscribe</button>
                                            </span>
                                        </div>
                                    </form>
                                </div>-->
            </div>
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->

<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-6 col-sm-6">
                <div class="copyright">2014-2015 © Black Pony Company, Nordi. ALL Rights Reserved.</div>
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN SOCIAL ICONS -->
            <div class="col-md-6 col-sm-6 pull-right">
                <ul class="social-icons">
                    <!--<li><a class="rss" data-original-title="rss" href="javascript:void(0);"></a></li>-->
                    <li><a class="facebook" data-original-title="facebook" href="javascript:void(0);"></a></li>
                    <li><a class="twitter" data-original-title="twitter" href="javascript:void(0);"></a></li>
                    <li><a class="googleplus" data-original-title="googleplus" href="javascript:void(0);"></a></li>
                    <!--<li><a class="linkedin" data-original-title="linkedin" href="javascript:void(0);"></a></li>-->
                    <li><a class="youtube" data-original-title="youtube" href="javascript:void(0);"></a></li>
                    <!--<li><a class="vimeo" data-original-title="vimeo" href="javascript:void(0);"></a></li>-->
                    <!--<li><a class="skype" data-original-title="skype" href="javascript:void(0);"></a></li>-->
                </ul>
            </div>
            <!-- END SOCIAL ICONS -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

<a href="#promo-block" class="go2top scroll"><i class="fa fa-arrow-up"></i></a>
